#!/bin/bash

pushd $(dirname ${BASH_SOURCE[0]})

SCRIPT_DIRNAME=$(basename ${PWD})


echo "----------------------------------------------"
echo "              STARTING ${SCRIPT_DIRNAME^^}    "
echo "                                              "
echo "   PATH ${PATH}                               "
echo "   BUNDLE: $(which bundle)                    "
echo "----------------------------------------------"


#echo "Start in development mode!"
#rerun 'rackup -o 0.0.0.0 -p 8003'
#popd

exec bundle exec rackup -o 0.0.0.0 -p 8003
